
<form action="/admin/sqlite/row/<?=$table?>/<?=$row->id??''?>" method="post">
    <div>
        <?php $c=1; foreach ($cols as $field=>$value): ?>
            <label>
                <span><?=$field?></span>
                <input type="text" name="<?=$field?>" placeholder value="<?=$row->$field??''?>">
            </label>
            <?php if ($c % 2 == 0): ?>
                </div><div>
            <?php endif; ?>
        <?php ++$c; endforeach; ?>
    </div>
    <div>
        <?php if ( ! empty($row->id)): ?>
            <button type="submit" data-color="red" name="action" value="delete"><?=_img::icon('md/remove')?> Delete</button>
        <?php endif; ?>
        <button type="submit" data-color="green" name="action" value="create"><?=_img::icon('md/add')?> Create</button>
        <?php if ( ! empty($row->id)): ?>
            <button type="submit" data-color="yellow" name="action" value="update"><?=_img::icon('md/save')?> Update</button>
        <?php endif; ?>
    </div>
</form>

<?php
include APP_PATH . 'views/admin/sqlite/rows.phtml';
