
<table>
    <caption>
        <a href="/admin/sqlite/table/<?=$table?>"><?=$table?> <?=_img::icon('md/edit')?></a>
    </caption>
    <thead>
        <tr>
            <th></th>
            <?php foreach ($cols as $col=>$val): ?>
                <th><?=$col?></th>
            <?php endforeach; ?>
            <th><a href="/admin/sqlite/field/<?=$table?>"><?=_img::icon('md/add')?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $row): ?>
            <tr>
                <td><a href="/admin/sqlite/row/<?=$table?>/<?=$row->id?>"><?=_img::icon('md/edit')?></a></td>
                <?php foreach ($row as $col=>$val): ?>
                    <td><?=$val?></td>
                <?php endforeach; ?>
                <td></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td><a href="/admin/sqlite/row/<?=$table?>"><?=_img::icon('md/add')?></a></td>
            <?php foreach ($cols as $col=>$val): ?>
                <td></td>
            <?php endforeach; ?>
            <td></td>
        </tr>
    </tbody>
</table>
