
<form action="/admin/sqlite/table/<?=$table?>" method="post">
    <fieldset>
        <header>
        </header>
        <section>
            <label>
                <span>Table name</span>
                <input type="text" name="name" placeholder value="<?=$table?>">
            </label>
        </section>
        <footer>
            <?php if ($table): ?>
                <button type="submit" data-color="red" name="action" value="delete"><?=_img::icon('md/remove')?> Delete</button>
            <?php endif; ?>
            <button type="submit" data-color="green" name="action" value="create"><?=_img::icon('md/add')?> Create</button>
            <?php if ($table): ?>
                <button type="submit" data-color="yellow" name="action" value="update"><?=_img::icon('md/save')?> Update</button>
            <?php endif; ?>
        </footer>
    </fieldset>
</form>

<?php
include APP_PATH . 'views/admin/sqlite/fields.phtml';
